language: python

python:
  - 3.6

before_install:
  - sudo apt-get install -qq libvirt-dev

install:
  - pip install -r requirements.txt

before_script:
  - chmod +x ./CI/before_script.sh && ./CI/before_script.sh

script: sudo env "PATH=$PATH" python engine.py test
